"use client";

import {
  Activity,
  AlertTriangle,
  Bell,
  Calendar,
  Check,
  Clock,
  Cloud,
  Copy,
  Crown,
  Download,
  Flame,
  Gauge,
  Gift,
  Globe,
  Heart,
  HelpCircle,
  Info,
  Key,
  Laptop,
  LifeBuoy,
  Link2,
  Lock,
  MessageSquare,
  Monitor,
  QrCode,
  Rocket,
  Send,
  Server,
  Settings,
  Shield,
  Smartphone,
  Sparkles,
  Star,
  Tablet,
  Upload,
  User,
  Users,
  Wifi,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  alert: AlertTriangle,
  bell: Bell,
  calendar: Calendar,
  check: Check,
  clock: Clock,
  cloud: Cloud,
  copy: Copy,
  crown: Crown,
  download: Download,
  flame: Flame,
  gauge: Gauge,
  gift: Gift,
  globe: Globe,
  heart: Heart,
  help: HelpCircle,
  info: Info,
  key: Key,
  laptop: Laptop,
  lifebuoy: LifeBuoy,
  link: Link2,
  lock: Lock,
  message: MessageSquare,
  monitor: Monitor,
  qr: QrCode,
  rocket: Rocket,
  send: Send,
  server: Server,
  settings: Settings,
  shield: Shield,
  smartphone: Smartphone,
  sparkles: Sparkles,
  star: Star,
  tablet: Tablet,
  upload: Upload,
  user: User,
  users: Users,
  wifi: Wifi,
  x: X,
  zap: Zap,
};

export const ICON_NAMES = Object.keys(ICONS);

export function NodeIcon({ name, size = 24, className, style }: { name: string; size?: number; className?: string; style?: React.CSSProperties }) {
  const C = ICONS[name] ?? Star;
  return <C size={size} className={className} style={style} aria-hidden />;
}
