package service

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"math"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"

	toml "github.com/pelletier/go-toml/v2"
)

// The catalog is generated by scripts/gen_telemt_catalog.py from Telemt's own
// docs/Config_params/CONFIG_PARAMS.ru.md, so every documented config.toml key can be set from
// the panel without hand-writing a form field for each one.
//
//go:embed telemt_params_catalog.json
var telemtParamCatalogJSON []byte

// TelemtParam describes one Telemt config.toml key.
type TelemtParam struct {
	Section   string `json:"section"`
	Key       string `json:"key"`
	Array     bool   `json:"array"`
	Type      string `json:"type"`
	Default   string `json:"default"`
	Hot       bool   `json:"hot"`
	Desc      string `json:"desc"`
	Valid     string `json:"valid"`
	Container bool   `json:"container"`
	Managed   bool   `json:"managed"`
	// Since is the first Telemt release that accepts this key ("" = every supported release).
	Since string `json:"since,omitempty"`
	// Kind is the value shape the panel edits and the backend validates:
	// bool | int | float | string | strlist | enum | object.
	Kind    string   `json:"kind"`
	Options []string `json:"options,omitempty"`
	Min     *float64 `json:"min,omitempty"`
	Max     *float64 `json:"max,omitempty"`
}

// ID is the "section.key" identifier used as the params map key ("" section = top level).
func (p TelemtParam) ID() string {
	if p.Section == "" {
		return p.Key
	}
	return p.Section + "." + p.Key
}

var (
	telemtCatalogOnce sync.Once
	telemtCatalog     []TelemtParam
	telemtCatalogByID map[string]*TelemtParam
)

var telemtEnumOptRe = regexp.MustCompile(`"([^"]+)"|\b(false|true)\b|\b(\d+)\b`)

func classifyTelemtParam(p *TelemtParam) {
	t := strings.TrimSpace(p.Type)
	switch {
	case p.Container:
		p.Kind = "object"
	case t == "bool":
		p.Kind = "bool"
	case t == "f32" || t == "f64":
		p.Kind = "float"
	case regexp.MustCompile(`^(u8|u16|u32|u64|usize|i32|i64|isize)$`).MatchString(t):
		p.Kind = "int"
		f := func(v float64) *float64 { return &v }
		switch t {
		case "u8":
			p.Min, p.Max = f(0), f(255)
		case "u16":
			p.Min, p.Max = f(0), f(65535)
		case "u32":
			p.Min, p.Max = f(0), f(4294967295)
		case "u64", "usize":
			p.Min = f(0)
		}
	case t == "String[]" || t == "IpNetwork[]" || t == "IpAddr[]" || t == "Path[]":
		p.Kind = "strlist"
	case strings.HasPrefix(t, "Map<") || strings.HasPrefix(t, "Table"):
		p.Kind = "object"
	case t == "String" || t == "Path" || t == "IpAddr" || t == "IpNetwork" || t == "SocketAddr":
		p.Kind = "string"
	case strings.Contains(t, `"*" or String[]`):
		p.Kind = "object" // accepts "*" or an array: edited as raw JSON
	case strings.HasPrefix(t, `"`) || strings.HasPrefix(t, "false") || regexp.MustCompile(`^\d( или | or )\d$`).MatchString(t):
		p.Kind = "enum"
		for _, m := range telemtEnumOptRe.FindAllStringSubmatch(t, -1) {
			for _, g := range m[1:] {
				if g != "" {
					p.Options = append(p.Options, g)
					break
				}
			}
		}
	default:
		p.Kind = "string"
	}
}

// TelemtParamCatalog returns every documented Telemt config key (parsed once).
func TelemtParamCatalog() []TelemtParam {
	telemtCatalogOnce.Do(func() {
		if err := json.Unmarshal(telemtParamCatalogJSON, &telemtCatalog); err != nil {
			panic(fmt.Sprintf("telemt params catalog: %v", err))
		}
		telemtCatalogByID = make(map[string]*TelemtParam, len(telemtCatalog))
		for i := range telemtCatalog {
			classifyTelemtParam(&telemtCatalog[i])
			// The same key can appear under several array sections; keep the first per ID.
			id := telemtCatalog[i].ID()
			if _, ok := telemtCatalogByID[id]; !ok {
				telemtCatalogByID[id] = &telemtCatalog[i]
			}
		}
	})
	return telemtCatalog
}

// telemtParamValue validates a raw JSON value against the catalog entry and converts it to the
// Go value that go-toml marshals to the right TOML type. (nil, nil) means "omit".
func telemtParamValue(p *TelemtParam, raw json.RawMessage) (any, error) {
	s := strings.TrimSpace(string(raw))
	if s == "" || s == "null" {
		return nil, nil
	}
	bad := func(want string) error { return fmt.Errorf("%s: expected %s", p.ID(), want) }
	switch p.Kind {
	case "bool":
		var v bool
		if err := json.Unmarshal(raw, &v); err != nil {
			return nil, bad("true/false")
		}
		return v, nil
	case "int":
		var n json.Number
		if err := json.Unmarshal(raw, &n); err != nil {
			return nil, bad("integer")
		}
		i, err := strconv.ParseInt(n.String(), 10, 64)
		if err != nil {
			f, ferr := strconv.ParseFloat(n.String(), 64)
			if ferr != nil || f != math.Trunc(f) || f < 0 || f > 1.8e19 {
				return nil, bad("integer")
			}
			// u64 above int64: TOML integers are signed 64-bit anyway.
			return nil, fmt.Errorf("%s: value too large", p.ID())
		}
		if p.Min != nil && float64(i) < *p.Min {
			return nil, fmt.Errorf("%s: must be >= %v", p.ID(), *p.Min)
		}
		if p.Max != nil && float64(i) > *p.Max {
			return nil, fmt.Errorf("%s: must be <= %v", p.ID(), *p.Max)
		}
		return i, nil
	case "float":
		var f float64
		if err := json.Unmarshal(raw, &f); err != nil {
			return nil, bad("number")
		}
		return f, nil
	case "string":
		var v string
		if err := json.Unmarshal(raw, &v); err != nil {
			return nil, bad("string")
		}
		v = strings.TrimSpace(v)
		if v == "" {
			return nil, nil
		}
		return v, nil
	case "strlist":
		var v []string
		if err := json.Unmarshal(raw, &v); err != nil {
			return nil, bad("list of strings")
		}
		out := make([]any, 0, len(v))
		for _, x := range v {
			if x = strings.TrimSpace(x); x != "" {
				out = append(out, x)
			}
		}
		if len(out) == 0 {
			return nil, nil
		}
		return out, nil
	case "enum":
		var anyv any
		if err := json.Unmarshal(raw, &anyv); err != nil {
			return nil, bad("one of the allowed values")
		}
		key := ""
		switch t := anyv.(type) {
		case string:
			key = t
		case bool:
			key = strconv.FormatBool(t)
		case float64:
			key = strconv.FormatInt(int64(t), 10)
		default:
			return nil, bad("one of the allowed values")
		}
		if key == "" {
			return nil, nil
		}
		for _, o := range p.Options {
			if o == key {
				switch t := anyv.(type) {
				case bool:
					return t, nil
				case float64:
					return int64(t), nil
				}
				if n, err := strconv.ParseInt(key, 10, 64); err == nil && !isTelemtStringEnum(p) {
					return n, nil
				}
				return key, nil
			}
		}
		return nil, fmt.Errorf("%s: %q is not one of %s", p.ID(), key, strings.Join(p.Options, ", "))
	default: // object: accepted as-is but must be a JSON object/array/string
		var anyv any
		if err := json.Unmarshal(raw, &anyv); err != nil {
			return nil, bad("JSON value")
		}
		return normalizeJSONForTOML(anyv), nil
	}
}

func isTelemtStringEnum(p *TelemtParam) bool {
	for _, o := range p.Options {
		if _, err := strconv.ParseInt(o, 10, 64); err != nil {
			return true
		}
	}
	return false
}

func normalizeJSONForTOML(v any) any {
	switch t := v.(type) {
	case float64:
		if t == math.Trunc(t) && math.Abs(t) < 1e15 {
			return int64(t)
		}
		return t
	case []any:
		out := make([]any, len(t))
		for i, x := range t {
			out[i] = normalizeJSONForTOML(x)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(t))
		for k, x := range t {
			out[k] = normalizeJSONForTOML(x)
		}
		return out
	}
	return v
}

// ValidateTelemtParams checks the operator's extra params: known keys only, correct value
// shapes, and nothing SharX manages itself.
func ValidateTelemtParams(params map[string]json.RawMessage) error {
	TelemtParamCatalog()
	for id, raw := range params {
		p, ok := telemtCatalogByID[id]
		if !ok {
			return fmt.Errorf("telemt params: unknown parameter %q", id)
		}
		if p.Array && !strings.HasPrefix(p.Section, "web.") {
			return fmt.Errorf("telemt params: %q belongs to an array of tables and cannot be set here", id)
		}
		if p.Managed {
			return fmt.Errorf("telemt params: %q is managed by SharX", id)
		}
		if p.Container {
			return fmt.Errorf("telemt params: %q is a table; set its individual keys", id)
		}
		if _, err := telemtParamValue(p, raw); err != nil {
			return fmt.Errorf("telemt params: %w", err)
		}
	}
	return nil
}

// ValidateTelemtUpstreams checks the operator's [[upstreams]] entries against the catalog.
func ValidateTelemtUpstreams(list []map[string]json.RawMessage) error {
	TelemtParamCatalog()
	for i, up := range list {
		typeRaw, ok := up["type"]
		if !ok {
			return fmt.Errorf("telemt upstreams[%d]: type is required", i)
		}
		var typ string
		_ = json.Unmarshal(typeRaw, &typ)
		switch typ {
		case "direct", "socks4", "socks5", "shadowsocks":
		default:
			return fmt.Errorf("telemt upstreams[%d]: unsupported type %q", i, typ)
		}
		for k, raw := range up {
			p := lookupTelemtArrayParam("upstreams", k)
			if p == nil {
				return fmt.Errorf("telemt upstreams[%d]: unknown key %q", i, k)
			}
			if _, err := telemtParamValue(p, raw); err != nil {
				return fmt.Errorf("telemt upstreams[%d]: %w", i, err)
			}
		}
	}
	return nil
}

func lookupTelemtArrayParam(section, key string) *TelemtParam {
	cat := TelemtParamCatalog()
	for i := range cat {
		if cat[i].Section == section && cat[i].Key == key {
			return &cat[i]
		}
	}
	return nil
}

// setTOMLPath writes value at path (segments) inside tree, fanning out over arrays of tables
// (e.g. web.vhosts.*, web.vhosts.profiles.*). An existing key is never overwritten: whatever
// SharX generated from its own typed form wins.
func setTOMLPath(node any, path []string, value any) {
	switch t := node.(type) {
	case map[string]any:
		if len(path) == 1 {
			if _, exists := t[path[0]]; !exists {
				t[path[0]] = value
			}
			return
		}
		child, ok := t[path[0]]
		if !ok {
			child = map[string]any{}
			t[path[0]] = child
		}
		setTOMLPath(child, path[1:], value)
	case []any:
		for _, el := range t {
			setTOMLPath(el, path, value)
		}
	}
}

// ApplyTelemtExtras merges the operator's extra params and upstreams into a generated TOML
// document. With nothing to add the input is returned byte-for-byte.
func ApplyTelemtExtras(tomlText string, params map[string]json.RawMessage, upstreams []map[string]json.RawMessage) (string, error) {
	if len(params) == 0 && len(upstreams) == 0 {
		return tomlText, nil
	}
	if err := ValidateTelemtParams(params); err != nil {
		return "", err
	}
	if err := ValidateTelemtUpstreams(upstreams); err != nil {
		return "", err
	}
	tree := map[string]any{}
	if err := toml.Unmarshal([]byte(tomlText), &tree); err != nil {
		return "", fmt.Errorf("telemt params: generated config is not valid TOML: %w", err)
	}
	ids := make([]string, 0, len(params))
	for id := range params {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		p := telemtCatalogByID[id]
		if _, hasWeb := tree["web"]; !hasWeb && strings.HasPrefix(id, "web.") {
			continue // WEB mode is off for this inbound: nothing to tune
		}
		v, err := telemtParamValue(p, params[id])
		if err != nil {
			return "", fmt.Errorf("telemt params: %w", err)
		}
		if v == nil {
			continue
		}
		path := []string{p.Key}
		if p.Section != "" {
			path = append(strings.Split(p.Section, "."), p.Key)
		}
		setTOMLPath(tree, path, v)
	}
	if len(upstreams) > 0 {
		if _, exists := tree["upstreams"]; !exists {
			arr := make([]any, 0, len(upstreams))
			for _, up := range upstreams {
				m := map[string]any{}
				for k, raw := range up {
					p := lookupTelemtArrayParam("upstreams", k)
					v, err := telemtParamValue(p, raw)
					if err != nil {
						return "", fmt.Errorf("telemt upstreams: %w", err)
					}
					if v != nil {
						m[k] = v
					}
				}
				arr = append(arr, m)
			}
			tree["upstreams"] = arr
		}
	}
	out, err := toml.Marshal(tree)
	if err != nil {
		return "", fmt.Errorf("telemt params: %w", err)
	}
	// Keep the generator header comment (toml.Marshal drops comments).
	header := ""
	for _, line := range strings.Split(tomlText, "\n") {
		if strings.HasPrefix(line, "#") {
			header += line + "\n"
			continue
		}
		break
	}
	return header + string(out), nil
}

// telemtVersionParts parses "3.5.7" / "v3.5.9-rc1" into numeric parts; ok=false when unparseable.
func telemtVersionParts(v string) (parts [3]int, ok bool) {
	v = strings.TrimPrefix(strings.TrimSpace(v), "v")
	if i := strings.IndexAny(v, "-+ "); i >= 0 {
		v = v[:i]
	}
	segs := strings.Split(v, ".")
	if len(segs) == 0 || segs[0] == "" {
		return parts, false
	}
	for i := 0; i < len(segs) && i < 3; i++ {
		n, err := strconv.Atoi(segs[i])
		if err != nil {
			return parts, false
		}
		parts[i] = n
	}
	return parts, true
}

// telemtVersionLess reports a < b; unknown/unparseable versions are never "less" (we do not
// block on versions we cannot read).
func telemtVersionLess(a, b string) bool {
	pa, oka := telemtVersionParts(a)
	pb, okb := telemtVersionParts(b)
	if !oka || !okb {
		return false
	}
	for i := 0; i < 3; i++ {
		if pa[i] != pb[i] {
			return pa[i] < pb[i]
		}
	}
	return false
}

// telemtParamsNeedingVersion returns the set params (id -> since) whose Telemt release is newer
// than have. Unknown versions yield none.
func telemtParamsNeedingVersion(params map[string]json.RawMessage, have string) map[string]string {
	TelemtParamCatalog()
	out := map[string]string{}
	for id := range params {
		if p, ok := telemtCatalogByID[id]; ok && p.Since != "" && telemtVersionLess(have, p.Since) {
			out[id] = p.Since
		}
	}
	return out
}

// stripUnsupportedTelemtParams returns settings JSON without the params the given Telemt build
// does not know (an old node keeps working instead of receiving a config it may reject).
func stripUnsupportedTelemtParams(settingsJSON, have string) (string, []string) {
	cfg := parseTelemtSettings(settingsJSON)
	bad := telemtParamsNeedingVersion(cfg.Params, have)
	if len(bad) == 0 {
		return settingsJSON, nil
	}
	var root map[string]json.RawMessage
	if err := json.Unmarshal([]byte(settingsJSON), &root); err != nil {
		return settingsJSON, nil
	}
	var tm map[string]json.RawMessage
	if err := json.Unmarshal(root["telemt"], &tm); err != nil {
		return settingsJSON, nil
	}
	kept := map[string]json.RawMessage{}
	names := make([]string, 0, len(bad))
	for id, raw := range cfg.Params {
		if _, drop := bad[id]; drop {
			names = append(names, id)
			continue
		}
		kept[id] = raw
	}
	sort.Strings(names)
	if len(kept) == 0 {
		delete(tm, "params")
	} else if b, err := json.Marshal(kept); err == nil {
		tm["params"] = b
	}
	tb, err := json.Marshal(tm)
	if err != nil {
		return settingsJSON, nil
	}
	root["telemt"] = tb
	rb, err := json.Marshal(root)
	if err != nil {
		return settingsJSON, nil
	}
	return string(rb), names
}
