// AUTO-GENERATED by scripts/gen-theme-palettes.mjs — do not edit.
export type ThemePalette = Record<"bg" | "bg-elevated" | "surface-strong" | "border" | "border-strong" | "fg" | "fg-muted" | "accent" | "accent-ambient", string>;

export const THEME_PALETTES: Record<string, ThemePalette> = {
  "web": {
    "bg": "#05060a",
    "bg-elevated": "#0c0f18",
    "surface-strong": "rgba(255, 255, 255, 0.08)",
    "border": "rgba(255, 255, 255, 0.1)",
    "border-strong": "rgba(255, 255, 255, 0.18)",
    "fg": "#f5f7fb",
    "fg-muted": "rgba(245, 247, 251, 0.66)",
    "accent": "#8577f2",
    "accent-ambient": "#6c52c7"
  },
  "default": {
    "bg": "#0d1117",
    "bg-elevated": "#1c2128",
    "surface-strong": "rgba(36, 44, 56, 0.85)",
    "border": "rgba(139, 148, 158, 0.15)",
    "border-strong": "rgba(34, 211, 238, 0.25)",
    "fg": "#c9d1d9",
    "fg-muted": "#8b949e",
    "accent": "#22d3ee",
    "accent-ambient": "#9775fa"
  },
  "midnight": {
    "bg": "#0a1628",
    "bg-elevated": "#0f1f35",
    "surface-strong": "rgba(30, 41, 59, 0.82)",
    "border": "rgba(148, 163, 184, 0.14)",
    "border-strong": "rgba(96, 165, 250, 0.28)",
    "fg": "#e2e8f0",
    "fg-muted": "#94a3b8",
    "accent": "#60a5fa",
    "accent-ambient": "#818cf8"
  },
  "ember": {
    "bg": "#140f0c",
    "bg-elevated": "#1f1814",
    "surface-strong": "rgba(55, 42, 36, 0.85)",
    "border": "rgba(214, 180, 150, 0.12)",
    "border-strong": "rgba(251, 191, 36, 0.22)",
    "fg": "#e8e0da",
    "fg-muted": "#b9a99a",
    "accent": "#f59e0b",
    "accent-ambient": "#f472b6"
  },
  "boreal": {
    "bg": "#0a1412",
    "bg-elevated": "#122620",
    "surface-strong": "rgba(32, 58, 52, 0.84)",
    "border": "rgba(134, 180, 168, 0.14)",
    "border-strong": "rgba(45, 212, 191, 0.24)",
    "fg": "#d8ebe6",
    "fg-muted": "#8eb5aa",
    "accent": "#14b8a6",
    "accent-ambient": "#22c55e"
  },
  "xuiClassic": {
    "bg": "#0a1222",
    "bg-elevated": "#151f31",
    "surface-strong": "rgba(34, 45, 66, 0.84)",
    "border": "rgba(44, 57, 80, 0.45)",
    "border-strong": "rgba(0, 135, 113, 0.32)",
    "fg": "rgba(255, 255, 255, 0.88)",
    "fg-muted": "#8b9cbb",
    "accent": "#008771",
    "accent-ambient": "#3ad3ba"
  },
  "starWars": {
    "bg": "#030508",
    "bg-elevated": "#0a0e18",
    "surface-strong": "rgba(18, 24, 42, 0.88)",
    "border": "rgba(255, 232, 31, 0.1)",
    "border-strong": "rgba(255, 232, 31, 0.28)",
    "fg": "#e8e4dc",
    "fg-muted": "#9aa3b8",
    "accent": "#ffe81f",
    "accent-ambient": "#c41e3a"
  },
  "vision": {
    "bg": "#f2f2f7",
    "bg-elevated": "rgba(255, 255, 255, 0.9)",
    "surface-strong": "rgba(255, 255, 255, 0.94)",
    "border": "rgba(0, 0, 0, 0.1)",
    "border-strong": "rgba(0, 0, 0, 0.14)",
    "fg": "#1c1c1e",
    "fg-muted": "#48484a",
    "accent": "#007aff",
    "accent-ambient": "#ff9f0a"
  },
  "helloKitty": {
    "bg": "#fff5f8",
    "bg-elevated": "rgba(255, 255, 255, 0.92)",
    "surface-strong": "rgba(255, 214, 224, 0.88)",
    "border": "rgba(219, 39, 119, 0.14)",
    "border-strong": "rgba(219, 39, 119, 0.28)",
    "fg": "#4a2c3a",
    "fg-muted": "#8a6572",
    "accent": "#ec4899",
    "accent-ambient": "#7dd3fc"
  },
  "barbie": {
    "bg": "#1a0a14",
    "bg-elevated": "#2b0f1e",
    "surface-strong": "rgba(224, 33, 138, 0.22)",
    "border": "rgba(255, 105, 180, 0.16)",
    "border-strong": "rgba(255, 105, 180, 0.34)",
    "fg": "#ffe6f2",
    "fg-muted": "#d998b8",
    "accent": "#ff2d92",
    "accent-ambient": "#ffd23f"
  }
};
