import type { CatalogItem } from "./catalog";
import { L, LP, MUTED, T, surface } from "./catalog-kit";
import { AC, AM, BAD, BD, FG, FM, FS, OK, SF, WARN, mk, mkSpec } from "./catalog-more-kit";

const link = (href: string, text: string, cls = "b") => `<a class="${cls}" href="${href}" target="_blank" rel="noopener">${text}</a>`;
const days = (l: "en" | "ru") => `{{ user.daysLeft | plural(${LP(l, "day", "день")}, ${LP(l, "days", "дня")}, ${LP(l, "days", "дней")}) }}`;

/** Status, connect, social, support, trust, hero and legal elements. */
export const CATALOG_MORE_B: CatalogItem[] = [
  // status
  mk("status-server", "info", ["Server status", "Online dot, uptime and ping (vars.uptime, vars.ping)"], ["Статус сервера", "Точка онлайн, аптайм и пинг (vars.uptime, vars.ping)"],
    (l) => `<div class="c"><div class="row"><span class="d"></span><h3>${L(l, "All systems operational", "Все системы работают")}</h3></div><div class="g"><div class="t"><small>${L(l, "Uptime", "Аптайм")}</small><b>{{ vars.uptime | default("99.9%") }}</b></div><div class="t"><small>${L(l, "Ping", "Пинг")}</small><b>{{ vars.ping | default("24 ms") }}</b></div><div class="t"><small>${L(l, "Connection", "Соединение")}</small><b>{{#if user.isOnline}}${L(l, "Online", "Онлайн")}{{else}}${L(l, "Idle", "Ожидание")}{{/if}}</b></div></div></div>`,
    `.d{width:12px;height:12px;border-radius:50%;background:${OK};box-shadow:0 0 0 0 ${OK};animation:pu 2s infinite}@keyframes pu{70%{box-shadow:0 0 0 10px transparent}100%{box-shadow:0 0 0 0 transparent}}`),
  mk("status-speed-tiles", "traffic", ["Speed and latency tiles", "Download, upload and ping tiles (vars.down, vars.up, vars.ping)"], ["Плитки скорости", "Загрузка, отдача и пинг (vars.down, vars.up, vars.ping)"],
    (l) => `<div class="g">${[["↓", L(l, "Download", "Загрузка"), "{{ vars.down | default('940') }}", L(l, "Mbps", "Мбит/с")], ["↑", L(l, "Upload", "Отдача"), "{{ vars.up | default('880') }}", L(l, "Mbps", "Мбит/с")], ["⚡", L(l, "Latency", "Задержка"), "{{ vars.ping | default('24') }}", L(l, "ms", "мс")]].map(([i, n, v, u]) => `<div class="t sp"><em>${i}</em><small>${n}</small><b>${v} <span class="m">${u}</span></b></div>`).join("")}</div>`,
    `.sp{position:relative;overflow:hidden}.sp em{font-style:normal;font-size:20px;color:${AC};animation:fl 2.4s ease-in-out infinite}.sp:nth-child(2) em{animation-delay:-.8s}.sp:nth-child(3) em{animation-delay:-1.6s}@keyframes fl{50%{transform:translateY(-4px);opacity:.6}}`),
  mk("status-maintenance", "info", ["Maintenance banner", "Warning strip shown when vars.notice is set"], ["Технические работы", "Предупреждение, если задана vars.notice"],
    (l) => `<div class="c mt"><span class="ic">🛠️</span><div><h3>${L(l, "Maintenance", "Технические работы")}</h3><p class="m">{{ vars.notice }}</p></div></div>`,
    `.mt{grid-template-columns:auto 1fr;align-items:center;border-color:${WARN};background:color-mix(in oklab,${WARN} 12%,transparent)}.ic{font-size:26px;animation:w 2.5s ease-in-out infinite}@keyframes w{50%{transform:rotate(-12deg)}}`),
  mkSpec("status-notice-visible", "info", "badge", ["Notice banner (conditional)", "Shown only when vars.notice is filled"], ["Объявление (по условию)", "Показывается только если заполнена vars.notice"],
    (l) => ["frame", { name: "Notice", visibleIf: "vars.notice", style: { ...surface, dir: "row", align: "center", bg: "color-mix(in oklab, var(--sub-warning, #d29922) 14%, transparent)", border: { w: 1, color: "var(--sub-warning, #d29922)" } } }, [
      ["icon", { name: "Icon", props: { name: "alert", size: 22 } }],
      T(L(l, "Notice", "Внимание") + ": {{ vars.notice }}", { fs: 14, fw: 500, grow: 1 }),
    ]]),
  mk("help-checklist", "info", ["Troubleshooting checklist", "Checked steps to try when it does not connect"], ["Чек-лист неполадок", "Что проверить, если не подключается"],
    (l) => `<div class="c"><h3>${L(l, "Not connecting? Check:", "Не подключается? Проверьте:")}</h3><ul>${[L(l, "The subscription is active and has traffic", "Подписка активна и есть трафик"), L(l, "The app has the latest subscription update", "В приложении обновлена подписка"), L(l, "Your device count is within the limit", "Число устройств в пределах лимита"), L(l, "Try another server or protocol", "Попробуйте другой сервер или протокол")].map((t, i) => `<li style="--i:${i}">${t}</li>`).join("")}</ul></div>`,
    `ul{list-style:none;margin:0;padding:0;display:grid;gap:8px}li{display:flex;gap:10px;align-items:center;opacity:0;animation:ci .5s calc(var(--i)*.25s) forwards}li:before{content:"✓";flex:none;width:22px;height:22px;border-radius:50%;display:grid;place-items:center;font-size:12px;font-weight:700;background:${OK};color:#04141a}@keyframes ci{from{opacity:0;transform:translateX(-8px)}to{opacity:1}}`),
  // connect
  mk("apps-download-cards", "connect", ["Download by platform", "iOS, Android, Windows, macOS, Linux (vars.iosUrl ...)"], ["Скачать по платформам", "iOS, Android, Windows, macOS, Linux (vars.iosUrl ...)"],
    (l) => `<div class="c"><h3>${L(l, "Get the app", "Скачайте приложение")}</h3><div class="g">${[["iosUrl", "🍎", "iOS"], ["androidUrl", "🤖", "Android"], ["windowsUrl", "🪟", "Windows"], ["macUrl", "💻", "macOS"], ["linuxUrl", "🐧", "Linux"]].map(([k, i, n]) => `{{#if vars.${k}}}<a class="t ap" href="{{ vars.${k} }}" target="_blank" rel="noopener"><em>${i}</em><b>${n}</b><small>${L(l, "Download", "Скачать")}</small></a>{{/if}}`).join("")}</div></div>`,
    `.ap{text-decoration:none;text-align:center;justify-items:center;transition:transform .2s,border-color .2s}.ap:hover{transform:translateY(-3px);border-color:${AC}}.ap em{font-style:normal;font-size:26px}.ap b{font-size:15px}`),
  mkSpec("connect-qr-steps", "connect", "qr", ["QR with steps", "QR code, Copy button and three quick steps"], ["QR с шагами", "QR-код, кнопка «Копировать» и три шага"],
    (l) => ["frame", { name: "QR steps", style: { ...surface, dir: "row", wrap: true, gap: 20, align: "center" } }, [
      ["qr", { name: "QR", props: { value: "{{ subscription.url }}", size: 160 } }],
      ["frame", { name: "Steps", style: { mode: "stack", dir: "column", gap: 10, pad: 0, grow: 1, w: "auto", minW: 200 } }, [
        T(L(l, "Connect by QR", "Подключение по QR"), { fs: 18, fw: 700 }, "h3"),
        T(L(l, "1. Install a VPN app", "1. Установите VPN-приложение"), { fs: 14, color: MUTED }),
        T(L(l, "2. Scan the code or copy the link", "2. Отсканируйте код или скопируйте ссылку"), { fs: 14, color: MUTED }),
        T(L(l, "3. Press Connect", "3. Нажмите «Подключить»"), { fs: 14, color: MUTED }),
        ["button", { name: "Copy", props: { label: L(l, "Copy link", "Копировать"), action: "copy", value: "{{ subscription.url }}", variant: "outline" }, style: { radius: 12, pad: [10, 14, 10, 14] } }],
      ]],
    ]]),
  mk("connect-telegram-cta", "connect", ["Telegram bot CTA", "Bot button and support channel (vars.tg, vars.channel)"], ["Telegram-бот", "Кнопка бота и канал поддержки (vars.tg, vars.channel)"],
    (l) => `<div class="c tg"><div class="row"><span class="lg">✈️</span><div><h3>${L(l, "Manage in Telegram", "Управляйте в Telegram")}</h3><p class="m">${L(l, "Renew, check traffic and get help in the bot.", "Продление, трафик и помощь прямо в боте.")}</p></div></div><div class="row">{{#if vars.tg}}${link("{{ vars.tg }}", L(l, "Open the bot", "Открыть бота"))}{{/if}}{{#if vars.channel}}${link("{{ vars.channel }}", L(l, "News channel", "Канал новостей"), "o")}{{/if}}</div></div>`,
    `.tg{background:linear-gradient(135deg,color-mix(in oklab,#2aabee 22%,transparent),${SF})}.lg{font-size:30px;animation:fy 3s ease-in-out infinite}@keyframes fy{50%{transform:translate(4px,-4px) rotate(8deg)}}`),
  mk("connect-sticky-cta", "connect", ["Sticky get-the-app bar", "Bottom-pinned look with the connect button"], ["Панель «Скачать» снизу", "Закреплённая снизу панель с кнопкой"],
    (l) => `<div class="bar2"><div><b>${L(l, "Ready to connect?", "Готовы подключиться?")}</b><small>{{ user.username | truncate(16) }} · ${days(l)}</small></div>${link("{{ subscription.url }}", L(l, "Connect", "Подключить"))}</div>`,
    `.bar2{position:sticky;bottom:12px;display:flex;justify-content:space-between;align-items:center;gap:12px;padding:12px 14px 12px 18px;border-radius:99px;border:1px solid ${BD};background:color-mix(in oklab,${SF} 70%,var(--sub-bg,#0d1117));backdrop-filter:blur(14px);box-shadow:0 12px 30px -10px rgba(0,0,0,.5);color:${FG}}.bar2 div{display:grid}.bar2 b{color:${FS}}.bar2 small{color:${FM};font-size:12px}.b{padding:10px 20px;border-radius:99px;background:${AC};color:#04141a;font-weight:700;text-decoration:none;animation:bt 2.4s ease-in-out infinite}@keyframes bt{50%{box-shadow:0 0 0 6px color-mix(in oklab,${AC} 25%,transparent)}}`),
  // faq / info
  mk("faq-cards", "info", ["FAQ cards", "Accordion with accent plus icons"], ["FAQ карточками", "Аккордеон с акцентными плюсами"],
    (l) => `<div class="fq">${[[L(l, "What is a subscription link?", "Что такое ссылка подписки?"), L(l, "A personal URL that gives your app all servers and updates them automatically.", "Личная ссылка, которая даёт приложению все серверы и обновляет их сама.")], [L(l, "Is my traffic logged?", "Ведутся ли логи?"), L(l, "We do not keep browsing logs.", "Мы не храним логи посещённых сайтов.")], [L(l, "How do I renew?", "Как продлить?"), L(l, "Use the Renew button or contact support.", "Нажмите «Продлить» или напишите в поддержку.")]].map(([q, a]) => `<details><summary>${q}</summary><p>${a}</p></details>`).join("")}</div>`,
    `.fq{display:grid;gap:10px}details{border:1px solid ${BD};border-radius:16px;padding:14px 16px;background:${SF};color:${FG}}summary{cursor:pointer;font-weight:600;color:${FS};list-style:none;display:flex;justify-content:space-between;gap:10px}summary::-webkit-details-marker{display:none}summary:after{content:"+";color:${AC};font-size:20px;line-height:1;transition:transform .25s}details[open] summary:after{transform:rotate(45deg)}details p{margin:10px 0 0;color:${FM};animation:fi .3s}@keyframes fi{from{opacity:0;transform:translateY(-4px)}}`),
  mk("faq-numbered", "info", ["FAQ numbered list", "Questions with big numbers"], ["FAQ с номерами", "Вопросы с крупными номерами"],
    (l) => `<div class="fq">${[[L(l, "The app says the subscription is empty", "Приложение пишет, что подписка пуста"), L(l, "Pull to refresh the subscription.", "Обновите подписку в приложении.")], [L(l, "Speed is slow", "Низкая скорость"), L(l, "Pick the nearest server.", "Выберите ближайший сервер.")], [L(l, "Can I use it on a router?", "Можно на роутере?"), L(l, "Yes, with a compatible client.", "Да, с совместимым клиентом.")]].map(([q, a], i) => `<details><summary><span class="n">0${i + 1}</span>${q}</summary><p>${a}</p></details>`).join("")}</div>`,
    `.fq{display:grid;gap:8px}details{padding:12px 4px;border-bottom:1px solid ${BD};color:${FG}}summary{cursor:pointer;font-weight:600;color:${FS};display:flex;gap:14px;align-items:center}.n{font-size:22px;font-weight:800;color:${AC};font-variant-numeric:tabular-nums}details p{margin:8px 0 0 44px;color:${FM}}`),
  mk("info-changelog", "info", ["News feed", "Timeline of updates"], ["Лента новостей", "Хронология обновлений"],
    (l) => `<div class="c"><h3>${L(l, "What is new", "Что нового")}</h3><ol>${[["12.03", L(l, "New servers in Netherlands and Germany", "Новые серверы в Нидерландах и Германии")], ["28.02", L(l, "Faster connection with the updated protocol", "Быстрее подключение с новым протоколом")], ["10.02", L(l, "Family sharing is here", "Появился семейный доступ")]].map(([d, t]) => `<li><time>${d}</time><span>${t}</span></li>`).join("")}</ol></div>`,
    `ol{list-style:none;margin:0;padding:0 0 0 16px;border-left:2px solid ${BD};display:grid;gap:14px}li{position:relative;display:grid;gap:2px}li:before{content:"";position:absolute;left:-23px;top:5px;width:10px;height:10px;border-radius:50%;background:${AC};box-shadow:0 0 0 4px color-mix(in oklab,${AC} 25%,transparent)}time{font-size:12px;color:${AC};font-weight:700}`),
  mk("info-how-it-works", "info", ["How it works grid", "Three feature columns with icons"], ["Как это работает", "Три колонки-преимущества с иконками"],
    (l) => `<div class="g3">${[["🔒", L(l, "Private", "Приватно"), L(l, "Traffic is encrypted end to end.", "Трафик шифруется от края до края.")], ["⚡", L(l, "Fast", "Быстро"), L(l, "Servers close to you.", "Серверы рядом с вами.")], ["🌍", L(l, "Open", "Свободно"), L(l, "Any site, any country.", "Любые сайты, любые страны.")]].map(([i, t, d]) => `<div class="c ft"><em>${i}</em><h4>${t}</h4><p class="m">${d}</p></div>`).join("")}</div>`,
    `.g3{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px}.ft{text-align:center;justify-items:center;transition:transform .25s}.ft:hover{transform:translateY(-4px)}.ft em{font-style:normal;font-size:30px;width:56px;height:56px;display:grid;place-items:center;border-radius:18px;background:color-mix(in oklab,${AC} 16%,transparent)}.ft h4{color:${FS};font-size:16px}`),
  // social
  mk("social-testimonials", "social", ["Testimonials", "Three short reviews"], ["Отзывы", "Три коротких отзыва"],
    (l) => `<div class="g3">${[[L(l, "Works great in every country I travel to.", "Отлично работает в любой стране."), "Anna"], [L(l, "Setup took one minute.", "Настроил за минуту."), "Max"], [L(l, "Finally stable streaming.", "Наконец-то стабильное видео."), "Ilya"]].map(([q, n]) => `<figure class="c"><blockquote>“${q}”</blockquote><figcaption>★★★★★ · ${n}</figcaption></figure>`).join("")}</div>`,
    `.g3{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}figure{margin:0}blockquote{margin:0;color:${FS};font-size:15px;line-height:1.5}figcaption{color:${WARN};font-size:12px}`),
  mk("social-proof-stats", "social", ["Social proof numbers", "Users, uptime and countries with count-up feel"], ["Социальное доказательство", "Пользователи, аптайм и страны"],
    (l) => `<div class="g">${[["50K+", L(l, "Happy users", "Пользователей")], ["99.9%", L(l, "Uptime", "Аптайм")], ["30+", L(l, "Countries", "Стран")]].map(([v, n]) => `<div class="t st"><b>${v}</b><small>${n}</small></div>`).join("")}</div>`,
    `.st{text-align:center}.st b{font-size:26px;background:linear-gradient(90deg,${AC},${AM});-webkit-background-clip:text;background-clip:text;color:transparent;animation:up .8s ease-out}@keyframes up{from{opacity:0;transform:translateY(8px)}}`),
  mk("social-links", "social", ["Social links row", "Round buttons for channels (vars.tg, vars.channel, vars.chatUrl)"], ["Ряд соцсетей", "Круглые кнопки каналов (vars.tg, vars.channel, vars.chatUrl)"],
    (l) => `<div class="c"><h3>${L(l, "Stay in touch", "Оставайтесь на связи")}</h3><div class="row">{{#if vars.tg}}<a class="o" href="{{ vars.tg }}" target="_blank" rel="noopener">✈️ Telegram</a>{{/if}}{{#if vars.channel}}<a class="o" href="{{ vars.channel }}" target="_blank" rel="noopener">📣 ${L(l, "Channel", "Канал")}</a>{{/if}}{{#if vars.chatUrl}}<a class="o" href="{{ vars.chatUrl }}" target="_blank" rel="noopener">💬 ${L(l, "Chat", "Чат")}</a>{{/if}}</div></div>`,
    `.o{border-radius:99px}.o:hover{border-color:${AC}}`),
  // trust
  mk("trust-badges", "info", ["Security badges", "No logs, AES-256, kill switch"], ["Значки безопасности", "Без логов, AES-256, kill switch"],
    (l) => `<div class="row bd">${[["🚫", L(l, "No logs", "Без логов")], ["🔐", "AES-256"], ["🛡️", L(l, "Kill switch", "Kill switch")], ["🌐", L(l, "No leaks", "Без утечек")]].map(([i, t]) => `<span><em>${i}</em>${t}</span>`).join("")}</div>`,
    `.bd{justify-content:center}.bd span{display:inline-flex;gap:8px;align-items:center;padding:8px 14px;border-radius:99px;border:1px solid ${BD};background:${SF};color:${FS};font-size:13px;font-weight:600}.bd em{font-style:normal}`),
  mk("trust-shield", "info", ["Trust shield card", "Shield with promise list"], ["Карточка доверия", "Щит и список обещаний"],
    (l) => `<div class="c sh"><div class="s">🛡️</div><div><h3>${L(l, "Your privacy first", "Приватность прежде всего")}</h3><p class="m">${L(l, "We never sell data and never log your traffic.", "Мы не продаём данные и не пишем ваш трафик.")}</p></div></div>`,
    `.sh{grid-template-columns:auto 1fr;align-items:center;gap:16px}.s{font-size:38px;width:72px;height:72px;display:grid;place-items:center;border-radius:22px;background:color-mix(in oklab,${OK} 18%,transparent);animation:br 3s ease-in-out infinite}@keyframes br{50%{transform:scale(1.08);box-shadow:0 0 30px -4px ${OK}}}`),
  // support
  mk("contact-tiles", "info", ["Contact tiles", "Telegram, email and chat (vars.tg, vars.email, vars.chatUrl)"], ["Контакты", "Telegram, почта и чат (vars.tg, vars.email, vars.chatUrl)"],
    (l) => `<div class="g">{{#if vars.tg}}<a class="t ap" href="{{ vars.tg }}" target="_blank" rel="noopener"><em>✈️</em><b>Telegram</b><small>${L(l, "Fastest reply", "Быстрый ответ")}</small></a>{{/if}}{{#if vars.email}}<a class="t ap" href="mailto:{{ vars.email }}"><em>✉️</em><b>Email</b><small>{{ vars.email }}</small></a>{{/if}}{{#if vars.chatUrl}}<a class="t ap" href="{{ vars.chatUrl }}" target="_blank" rel="noopener"><em>💬</em><b>${L(l, "Live chat", "Онлайн-чат")}</b><small>${L(l, "Daily", "Ежедневно")}</small></a>{{/if}}</div>`,
    `.ap{text-decoration:none;justify-items:center;text-align:center;transition:transform .2s,border-color .2s}.ap:hover{transform:translateY(-3px);border-color:${AC}}.ap em{font-style:normal;font-size:26px}.ap small{overflow-wrap:anywhere}`),
  // hero
  mk("hero-gradient", "hero", ["Hero: gradient", "Big greeting, days left and status"], ["Герой: градиент", "Крупное приветствие, дни и статус"],
    (l) => `<div class="c hg"><small>${L(l, "Welcome back", "С возвращением")}</small><h3>{{ user.username | truncate(22) }}</h3><p>{{#if user.neverExpires}}∞{{else}}{{ user.daysLeft }} ${days(l)} ${L(l, "left", "осталось")}{{/if}}</p></div>`,
    `.hg{padding:32px 24px;background:linear-gradient(135deg,color-mix(in oklab,${AC} 45%,transparent),color-mix(in oklab,${AM} 40%,transparent));border:0}.hg h3{font-size:clamp(26px,7vw,40px);font-weight:800}.hg p{font-size:16px;color:${FS}}`),
  mk("hero-glass", "hero", ["Hero: glass", "Frosted panel over glowing blobs"], ["Герой: стекло", "Матовая панель на светящихся пятнах"],
    (l) => `<div class="c hs"><i></i><i></i><div class="in"><h3>{{ user.username | truncate(22) }}</h3><p class="m">${L(l, "Your private connection is active", "Ваше приватное подключение активно")}</p></div></div>`,
    `.hs{padding:0;min-height:150px}.hs i{position:absolute;width:160px;height:160px;border-radius:50%;filter:blur(40px);background:${AC};opacity:.5;left:-30px;top:-30px;animation:bl 8s ease-in-out infinite alternate}.hs i+i{background:${AM};left:auto;right:-30px;top:auto;bottom:-40px;animation-delay:-4s}.in{position:relative;margin:20px;padding:20px;border-radius:18px;backdrop-filter:blur(16px);background:color-mix(in oklab,${SF} 70%,transparent);border:1px solid ${BD}}@keyframes bl{to{transform:translate(40px,30px) scale(1.2)}}`),
  mk("hero-minimal", "hero", ["Hero: minimal", "Just the name and a thin accent line"], ["Герой: минимал", "Только имя и тонкая линия"],
    (l) => `<div class="hm"><small>${L(l, "Hello", "Привет")}</small><h3>{{ user.username | truncate(24) }}</h3><i></i></div>`,
    `.hm{display:grid;gap:6px;padding:8px 2px;color:${FG}}.hm small{color:${FM};text-transform:uppercase;letter-spacing:.12em;font-size:12px}.hm h3{margin:0;font-size:clamp(28px,8vw,44px);color:${FS};font-weight:800}.hm i{display:block;width:60px;height:3px;border-radius:3px;background:${AC};animation:gr 2s ease-out}@keyframes gr{from{width:0}}`),
  mk("hero-mesh", "hero", ["Hero: animated mesh", "Moving mesh gradient background"], ["Герой: анимированная сетка", "Живой градиентный фон"],
    (l) => `<div class="c hx"><h3>${L(l, "You are protected", "Вы под защитой")}</h3><p>{{ user.username | truncate(22) }} · {{ user.userStatus }}</p></div>`,
    `.hx{min-height:150px;align-content:center;justify-items:center;text-align:center;border:0;background:radial-gradient(at 20% 20%,${AC} 0,transparent 50%),radial-gradient(at 80% 30%,${AM} 0,transparent 50%),radial-gradient(at 50% 90%,color-mix(in oklab,${AC} 60%,${AM}) 0,transparent 55%),var(--sub-bg,#0d1117);background-size:200% 200%;animation:ms 10s ease-in-out infinite alternate}.hx h3{font-size:26px;color:#fff}.hx p{color:rgba(255,255,255,.85)}@keyframes ms{to{background-position:100% 100%}}`),
  // legal
  mk("legal-footer", "decor", ["Legal footer", "Terms and privacy links (vars.termsUrl, vars.privacyUrl)"], ["Юридический подвал", "Ссылки на условия и приватность (vars.termsUrl, vars.privacyUrl)"],
    (l) => `<div class="lf"><div class="row">{{#if vars.termsUrl}}<a href="{{ vars.termsUrl }}" target="_blank" rel="noopener">${L(l, "Terms of service", "Условия использования")}</a>{{/if}}{{#if vars.privacyUrl}}<a href="{{ vars.privacyUrl }}" target="_blank" rel="noopener">${L(l, "Privacy policy", "Политика конфиденциальности")}</a>{{/if}}</div><small>© {{ now | date("YYYY") }} {{ branding.title }}</small></div>`,
    `.lf{display:grid;gap:8px;justify-items:center;padding-top:12px;border-top:1px solid ${BD};color:${FM}}.lf .row{justify-content:center;gap:16px}.lf a{color:${FM};font-size:13px;text-decoration:underline}.lf a:hover{color:${AC}}.lf small{font-size:12px}`),
];
void BAD; void MUTED;
