import type { CatalogItem } from "./catalog";
import { A, L, sceneItem } from "./catalog-kit";

type Act = [id: string, en: string, ru: string, icon: string, x: number, y: number, tone?: string];
/** [en, ru, show, focus, flows] — ids space separated, flows "a>b" or "a>b:tone". */
type Stp = [en: string, ru: string, show: string, focus?: string, flows?: string];

function scene(id: string, en: [string, string], ru: [string, string], acts: Act[], links: string, steps: Stp[], stepMs = 2600, height = 240): CatalogItem {
  return {
    id, cat: "scenes", icon: "scene", en, ru,
    build: (l) => sceneItem(l, en[0], {
      stepMs, height,
      actors: acts.map((a) => A(a[0], a[1], a[2], a[3], a[4], a[5], a[6], l)),
      links: links.split(" ").map((p) => p.split(">")),
      steps: steps.map((s) => ({
        caption: L(l, s[0], s[1]),
        show: s[2].split(" "),
        ...(s[3] ? { focus: s[3].split(" ") } : {}),
        ...(s[4] ? { flows: s[4].split(" ").map((f) => { const [p, tone] = f.split(":"); const [from, to] = p.split(">"); return { from, to, ...(tone ? { tone } : {}) }; }) } : {}),
      })),
    }),
  };
}

export const CATALOG_SCENES: CatalogItem[] = [
  scene("scene-killswitch", ["Scene: kill switch", "Connection drops, traffic is blocked, then restored"], ["Сцена: kill switch", "Обрыв связи, блокировка трафика, восстановление"],
    [["dev", "Device", "Устройство", "smartphone", 12, 50], ["vpn", "VPN tunnel", "VPN-туннель", "shield", 46, 50, "green"], ["net", "Internet", "Интернет", "globe", 88, 50, "blue"], ["ks", "Kill switch", "Kill switch", "lock", 46, 16, "rose"]],
    "dev>vpn vpn>net ks>vpn",
    [["Traffic flows through the tunnel", "Трафик идёт через туннель", "dev vpn net", "vpn", "dev>vpn:green vpn>net:green"],
     ["The connection suddenly drops", "Соединение внезапно обрывается", "dev vpn net", "vpn", "dev>vpn:rose"],
     ["Kill switch blocks all traffic, nothing leaks", "Kill switch блокирует весь трафик, утечек нет", "dev vpn net ks", "ks", "ks>vpn:rose"],
     ["The app reconnects and traffic resumes", "Приложение переподключается, трафик возобновляется", "dev vpn net ks", "vpn", "dev>vpn:green vpn>net:green"]]),
  scene("scene-split", ["Scene: split tunneling", "Some apps via VPN, others direct"], ["Сцена: раздельное туннелирование", "Часть приложений через VPN, часть напрямую"],
    [["dev", "Device", "Устройство", "smartphone", 10, 50], ["ap1", "Messenger", "Мессенджер", "message", 40, 20, "green"], ["ap2", "Bank app", "Банк", "lock", 40, 80, "amber"], ["vpn", "VPN node", "VPN-узел", "shield", 68, 20, "green"], ["net", "Internet", "Интернет", "globe", 90, 50, "blue"]],
    "dev>ap1 dev>ap2 ap1>vpn vpn>net ap2>net",
    [["Your device runs several apps", "На устройстве запущено несколько приложений", "dev ap1 ap2", "dev"],
     ["Chosen apps go through the VPN", "Выбранные приложения идут через VPN", "dev ap1 ap2 vpn", "ap1 vpn", "dev>ap1:green ap1>vpn:green"],
     ["Others connect directly, bypassing it", "Остальные соединяются напрямую, минуя VPN", "dev ap1 ap2 vpn net", "ap2", "dev>ap2:amber ap2>net:amber"],
     ["You decide in the app settings", "Вы сами решаете это в настройках приложения", "dev ap1 ap2 vpn net", "vpn net", "vpn>net:green"]]),
  scene("scene-balancer", ["Scene: node failover", "Balancer shifts traffic when a node fails"], ["Сцена: отказоустойчивость узлов", "Балансировщик переносит трафик при сбое узла"],
    [["dev", "Device", "Устройство", "laptop", 10, 50], ["lb", "Balancer", "Балансировщик", "settings", 38, 50, "accent"], ["na", "Node A", "Узел A", "server", 68, 22, "green"], ["nb", "Node B", "Узел B", "server", 68, 78, "green"], ["net", "Internet", "Интернет", "globe", 92, 50, "blue"]],
    "dev>lb lb>na lb>nb na>net nb>net",
    [["The balancer picks a healthy node", "Балансировщик выбирает исправный узел", "dev lb na nb net", "lb", "dev>lb lb>na:green na>net:green"],
     ["Node A goes down", "Узел A выходит из строя", "dev lb na nb net", "na", "lb>na:rose"],
     ["Traffic shifts to Node B automatically", "Трафик автоматически переходит на узел B", "dev lb na nb net", "nb", "dev>lb lb>nb:green nb>net:green"],
     ["You stay connected, no action needed", "Вы остаётесь на связи, ничего делать не нужно", "dev lb nb net", "dev net", "nb>net:green"]], 2800, 260),
  scene("scene-expiry", ["Scene: expiry and renewal", "What happens when the subscription ends"], ["Сцена: окончание и продление", "Что происходит, когда подписка заканчивается"],
    [["cl", "You", "Вы", "user", 10, 50], ["cal", "{{ user.daysLeft }} days left", "Осталось дней: {{ user.daysLeft }}", "calendar", 38, 50, "amber"], ["off", "Access paused", "Доступ приостановлен", "x", 66, 22, "rose"], ["pay", "Renew", "Продлить", "rocket", 66, 78, "green"], ["on", "Access restored", "Доступ восстановлен", "check", 90, 50, "green"]],
    "cl>cal cal>off cal>pay pay>on",
    [["You have {{ user.daysLeft }} days left", "У вас осталось дней: {{ user.daysLeft }}", "cl cal", "cal", "cl>cal:amber"],
     ["When the time runs out, access pauses", "Когда время выйдет, доступ приостановится", "cl cal off", "off", "cal>off:rose"],
     ["Renew at any moment", "Продлить можно в любой момент", "cl cal off pay", "pay", "cal>pay:green"],
     ["Access comes back right away", "Доступ возвращается сразу", "cl cal off pay on", "on", "pay>on:green"]]),
  scene("scene-setup-ios", ["Scene: setup on iPhone", "Install the app, add the link, connect"], ["Сцена: настройка на iPhone", "Установить приложение, добавить ссылку, подключиться"],
    [["ph", "iPhone", "iPhone", "smartphone", 10, 50], ["st", "App Store", "App Store", "download", 34, 50, "blue"], ["sub", "Subscription link", "Ссылка подписки", "link", 60, 50, "amber"], ["on", "Connected", "Подключено", "shield", 88, 50, "green"]],
    "ph>st st>sub sub>on",
    [["Take your iPhone", "Возьмите iPhone", "ph", "ph"],
     ["Install the app from the App Store", "Установите приложение из App Store", "ph st", "st", "ph>st:blue"],
     ["Paste your subscription link", "Вставьте ссылку подписки", "ph st sub", "sub", "st>sub:amber"],
     ["Tap Connect, you are protected", "Нажмите «Подключить», вы под защитой", "ph st sub on", "on", "sub>on:green"]], 2600, 220),
  scene("scene-setup-android", ["Scene: setup on Android", "Install, import the subscription, connect"], ["Сцена: настройка на Android", "Установка, импорт подписки, подключение"],
    [["ph", "Android", "Android", "smartphone", 10, 50], ["st", "Google Play", "Google Play", "download", 34, 50, "blue"], ["sub", "Import", "Импорт", "link", 60, 50, "amber"], ["on", "Connected", "Подключено", "shield", 88, 50, "green"]],
    "ph>st st>sub sub>on",
    [["Take your Android phone", "Возьмите Android-телефон", "ph", "ph"],
     ["Install the app from Google Play", "Установите приложение из Google Play", "ph st", "st", "ph>st:blue"],
     ["Import the subscription by link", "Импортируйте подписку по ссылке", "ph st sub", "sub", "st>sub:amber"],
     ["Connect with one tap", "Подключитесь одним нажатием", "ph st sub on", "on", "sub>on:green"]], 2600, 220),
  scene("scene-setup-windows", ["Scene: setup on Windows", "Download the client, add subscription, connect"], ["Сцена: настройка на Windows", "Скачать клиент, добавить подписку, подключиться"],
    [["pc", "Windows PC", "Компьютер", "monitor", 10, 50], ["dl", "Download client", "Скачать клиент", "download", 34, 50, "blue"], ["sub", "Add subscription", "Добавить подписку", "key", 60, 50, "amber"], ["on", "Protected", "Защита", "shield", 88, 50, "green"]],
    "pc>dl dl>sub sub>on",
    [["Open your computer", "Откройте компьютер", "pc", "pc"],
     ["Download and install the client", "Скачайте и установите клиент", "pc dl", "dl", "pc>dl:blue"],
     ["Add your subscription", "Добавьте свою подписку", "pc dl sub", "sub", "dl>sub:amber"],
     ["Switch on the connection", "Включите подключение", "pc dl sub on", "on", "sub>on:green"]], 2600, 220),
  scene("scene-sub-update", ["Scene: subscription update", "The app fetches fresh servers automatically"], ["Сцена: обновление подписки", "Приложение само получает свежие серверы"],
    [["app", "App", "Приложение", "smartphone", 12, 50], ["sub", "Subscription URL", "Ссылка подписки", "link", 42, 50, "amber"], ["new", "New servers", "Новые серверы", "server", 72, 22, "green"], ["ok", "Up to date", "Актуально", "check", 88, 78, "green"]],
    "app>sub sub>new new>app app>ok",
    [["The app knows your subscription link", "Приложение знает вашу ссылку подписки", "app sub", "sub"],
     ["It periodically asks for updates", "Оно периодически запрашивает обновления", "app sub", "app", "app>sub:amber"],
     ["New servers arrive in the list", "Новые серверы появляются в списке", "app sub new", "new", "sub>new:green"],
     ["Nothing to reinstall, all is current", "Ничего переустанавливать не нужно, всё актуально", "app sub new ok", "ok", "new>app:green app>ok:green"]]),
  scene("scene-speed", ["Scene: speed path", "Device to nearest node to internet"], ["Сцена: путь скорости", "Устройство, ближайший узел, интернет"],
    [["dev", "Device", "Устройство", "smartphone", 10, 50], ["nn", "Nearest node", "Ближайший узел", "server", 45, 50, "green"], ["far", "Distant node", "Дальний узел", "server", 45, 84, "rose"], ["net", "Internet", "Интернет", "globe", 88, 50, "blue"], ["ms", "Low latency", "Малая задержка", "gauge", 45, 16, "accent"]],
    "dev>nn nn>net dev>far",
    [["Speed depends on the path length", "Скорость зависит от длины пути", "dev nn net", "dev"],
     ["The nearest node keeps latency low", "Ближайший узел даёт малую задержку", "dev nn net ms", "nn ms", "dev>nn:green nn>net:green"],
     ["A distant node adds delay", "Дальний узел добавляет задержку", "dev nn net far", "far", "dev>far:rose"],
     ["Pick the closest location", "Выбирайте ближайшую локацию", "dev nn net ms", "nn", "nn>net:green"]], 2800, 260),
  scene("scene-family", ["Scene: family devices", "Family devices share one slot limit"], ["Сцена: устройства семьи", "Устройства семьи делят один лимит слотов"],
    [["me", "You", "Вы", "user", 12, 22, "accent"], ["kid", "Family", "Семья", "users", 12, 78, "accent"], ["slots", "{{ devices.max }} slots", "Слотов: {{ devices.max }}", "lock", 50, 50, "blue"], ["d1", "Phone", "Телефон", "smartphone", 88, 22, "green"], ["d2", "Tablet", "Планшет", "tablet", 88, 50, "green"], ["d3", "Laptop", "Ноутбук", "laptop", 88, 78, "green"]],
    "me>slots kid>slots slots>d1 slots>d2 slots>d3",
    [["One subscription has {{ devices.max }} device slots", "У подписки слотов устройств: {{ devices.max }}", "slots", "slots"],
     ["You use some of them", "Часть слотов занимаете вы", "slots me d1", "me d1", "me>slots:green slots>d1:green"],
     ["Family members use the rest", "Остальные заняты семьёй", "slots me kid d1 d2 d3", "kid", "kid>slots:green slots>d2:green slots>d3:green"],
     ["Free a slot to add another device", "Освободите слот, чтобы добавить устройство", "slots me kid d1 d2 d3", "slots"]], 2800, 280),
  scene("scene-support", ["Scene: support flow", "Problem, support, fix"], ["Сцена: обращение в поддержку", "Проблема, поддержка, решение"],
    [["you", "You", "Вы", "user", 10, 50], ["bug", "Problem", "Проблема", "alert", 34, 50, "rose"], ["sup", "Support", "Поддержка", "lifebuoy", 62, 50, "blue"], ["fix", "Fixed", "Решено", "check", 90, 50, "green"]],
    "you>bug bug>sup sup>fix",
    [["Something does not work", "Что-то не работает", "you bug", "bug", "you>bug:rose"],
     ["Write to support with details", "Напишите в поддержку с подробностями", "you bug sup", "sup", "bug>sup:blue"],
     ["We look into it and reply", "Мы разберёмся и ответим", "you bug sup", "sup", "sup>you:blue"],
     ["Problem solved, you are back online", "Проблема решена, вы снова онлайн", "you bug sup fix", "fix", "sup>fix:green"]], 2800, 220),
  scene("scene-security", ["Scene: security layers", "Encryption and DPI bypass"], ["Сцена: уровни защиты", "Шифрование и обход DPI"],
    [["dev", "Device", "Устройство", "laptop", 10, 50], ["enc", "Encryption", "Шифрование", "lock", 36, 50, "green"], ["dpi", "DPI filter", "DPI-фильтр", "alert", 62, 22, "rose"], ["mask", "Traffic masking", "Маскировка", "sparkles", 62, 78, "accent"], ["net", "Internet", "Интернет", "globe", 90, 50, "blue"]],
    "dev>enc enc>mask enc>dpi mask>net",
    [["Your data leaves the device", "Данные покидают устройство", "dev", "dev"],
     ["First it is encrypted", "Сначала они шифруются", "dev enc", "enc", "dev>enc:green"],
     ["Filters cannot read it", "Фильтры не могут его прочитать", "dev enc dpi", "dpi", "enc>dpi:rose"],
     ["Masked traffic passes through", "Замаскированный трафик проходит", "dev enc dpi mask net", "mask net", "enc>mask:accent mask>net:green"]], 2800, 260),
  scene("scene-reset", ["Scene: monthly traffic reset", "Usage counter resets each period"], ["Сцена: ежемесячный сброс трафика", "Счётчик обнуляется каждый период"],
    [["use", "Used", "Использовано", "activity", 14, 50, "amber"], ["rem", "{{ user.remaining }} left", "Осталось: {{ user.remaining }}", "gauge", 42, 50, "accent"], ["cal", "New period", "Новый период", "calendar", 70, 50, "blue"], ["zero", "Counter reset", "Счётчик сброшен", "check", 90, 50, "green"]],
    "use>rem rem>cal cal>zero",
    [["You use traffic during the month", "Вы расходуете трафик в течение месяца", "use", "use"],
     ["Remaining: {{ user.remaining }}", "Остаток: {{ user.remaining }}", "use rem", "rem", "use>rem:amber"],
     ["A new period begins", "Начинается новый период", "use rem cal", "cal", "rem>cal:blue"],
     ["The counter resets to zero", "Счётчик обнуляется", "use rem cal zero", "zero", "cal>zero:green"]], 2800, 220),
  scene("scene-qr", ["Scene: QR onboarding", "Scan a QR, the app opens, connected"], ["Сцена: подключение по QR", "Сканируйте QR, приложение откроется, вы подключены"],
    [["qr", "QR code", "QR-код", "qr", 12, 50, "accent"], ["ph", "Phone camera", "Камера телефона", "smartphone", 38, 50], ["app", "App opens", "Открывается приложение", "download", 64, 50, "blue"], ["on", "Connected", "Подключено", "shield", 90, 50, "green"]],
    "qr>ph ph>app app>on",
    [["Open the QR code from your page", "Откройте QR-код на странице", "qr", "qr"],
     ["Scan it with the phone camera", "Отсканируйте его камерой телефона", "qr ph", "ph", "qr>ph:accent"],
     ["The app opens with the subscription", "Приложение открывается с подпиской", "qr ph app", "app", "ph>app:blue"],
     ["Connected in seconds", "Подключение за секунды", "qr ph app on", "on", "app>on:green"]], 2400, 220),
  scene("scene-hero-shield", ["Scene: hero shield", "Compact: you, protection, internet"], ["Сцена: щит (компактно)", "Компактно: вы, защита, интернет"],
    [["you", "You", "Вы", "user", 16, 50], ["sh", "Protected", "Под защитой", "shield", 50, 50, "green"], ["net", "Internet", "Интернет", "globe", 84, 50, "blue"]],
    "you>sh sh>net",
    [["Private by default", "Приватно по умолчанию", "you sh", "sh", "you>sh:green"],
     ["Open and unrestricted", "Свободно и без ограничений", "you sh net", "net", "sh>net:blue"],
     ["Only you see your traffic", "Ваш трафик видите только вы", "you sh net", "you sh"],
     ["Always on, always safe", "Всегда включено и безопасно", "you sh net", "sh", "you>sh:green sh>net:green"]], 2200, 200),
];
