package render

import (
	"fmt"
	"strings"

	"github.com/konstpic/sharx-code/v2/balancer/spec"
)

// HAProxySocket is the runtime API socket the agent reads statistics from.
const HAProxySocket = "/var/run/sharx-haproxy.sock"

func haproxy(s spec.Spec) string {
	var b strings.Builder
	b.WriteString("# Generated by the SharX balancer agent. Do not edit.\n")
	b.WriteString("global\n")
	b.WriteString("    log stdout format raw local0\n")
	b.WriteString("    maxconn 50000\n")
	fmt.Fprintf(&b, "    stats socket %s mode 600 level admin\n", HAProxySocket)
	b.WriteString("\ndefaults\n")
	b.WriteString("    mode tcp\n    log global\n    option tcplog\n    option dontlognull\n")
	b.WriteString("    timeout connect 5s\n    timeout client 1h\n    timeout server 1h\n    timeout check 3s\n")
	b.WriteString("    default-server init-addr last,libc,none\n")
	// A peer that vanished without FIN/RST (phone out of coverage, dead node, dropped route) must not hold a session
	// for the whole 1h idle timeout, together with the backend socket behind it. Keepalive probes after 60s idle,
	// every 15s, 4 misses: a dead peer is dropped in about two minutes on both legs.
	b.WriteString("    option clitcpka\n    option srvtcpka\n")
	b.WriteString("    clitcpka-idle 60s\n    clitcpka-intvl 15s\n    clitcpka-cnt 4\n")
	b.WriteString("    srvtcpka-idle 60s\n    srvtcpka-intvl 15s\n    srvtcpka-cnt 4\n")
	for _, p := range s.Pools {
		if p.Proto != spec.ProtoTCP {
			continue
		}
		fmt.Fprintf(&b, "\nfrontend fe_%d\n", p.ID)
		fmt.Fprintf(&b, "    bind :%d\n", p.ListenPort)
		fmt.Fprintf(&b, "    default_backend be_%d\n", p.ID)
		fmt.Fprintf(&b, "\nbackend be_%d\n", p.ID)
		switch p.Algorithm {
		case spec.AlgoLeastConn:
			b.WriteString("    balance leastconn\n")
		case spec.AlgoSource:
			b.WriteString("    balance source\n")
		default:
			b.WriteString("    balance roundrobin\n")
		}
		for i, m := range p.Members {
			line := fmt.Sprintf("    server s%d %s weight %d", i, backendAddr(m), weightOf(m))
			if p.HealthCheck {
				line += " check inter 3s fall 2 rise 2"
			}
			if m.Backup {
				line += " backup"
			}
			if p.ProxyProtocol {
				line += " send-proxy-v2"
			}
			b.WriteString(line + "\n")
		}
	}
	return b.String()
}
