package render

import (
	"fmt"
	"strings"

	"github.com/konstpic/sharx-code/v2/balancer/spec"
)

func nginx(s spec.Spec) string {
	var b strings.Builder
	b.WriteString("# Generated by the SharX balancer agent. Do not edit.\n")
	b.WriteString("load_module /usr/lib/nginx/modules/ngx_stream_module.so;\n")
	b.WriteString("worker_processes auto;\nerror_log /dev/stderr warn;\npid /run/sharx-nginx.pid;\n")
	b.WriteString("events { worker_connections 16384; }\n\nstream {\n")
	for _, p := range s.Pools {
		fmt.Fprintf(&b, "    upstream up_%d {\n", p.ID)
		// A shared zone makes round robin, least_conn and failure counters common to all workers.
		fmt.Fprintf(&b, "        zone up_%d 128k;\n", p.ID)
		switch p.Algorithm {
		case spec.AlgoLeastConn:
			b.WriteString("        least_conn;\n")
		case spec.AlgoSource:
			b.WriteString("        hash $remote_addr consistent;\n")
		}
		for _, m := range p.Members {
			line := fmt.Sprintf("        server %s weight=%d", backendAddr(m), weightOf(m))
			if p.HealthCheck {
				line += " max_fails=2 fail_timeout=10s"
			}
			if m.Backup {
				line += " backup"
			}
			b.WriteString(line + ";\n")
		}
		b.WriteString("    }\n")
		b.WriteString("    server {\n")
		if p.Proto == spec.ProtoUDP {
			fmt.Fprintf(&b, "        listen %d udp;\n", p.ListenPort)
			b.WriteString("        proxy_timeout 10m;\n")
		} else {
			fmt.Fprintf(&b, "        listen %d;\n", p.ListenPort)
			b.WriteString("        proxy_timeout 1h;\n")
			if p.ProxyProtocol {
				b.WriteString("        proxy_protocol on;\n")
			}
		}
		b.WriteString("        proxy_connect_timeout 3s;\n")
		fmt.Fprintf(&b, "        proxy_pass up_%d;\n    }\n", p.ID)
	}
	b.WriteString("}\n")
	return b.String()
}
